+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "2966"
    creation_ts: 2015-09-25 08:08:00 +0200
    short_desc: ft_databrowser not creating cfg.headerfile for EDF
    delta_ts: 2016-06-14 16:14:53 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: PC
    op_sys: Mac OS
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    assigned_to:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    cc: bick35
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "16131"
        comment_count: "0"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2015-09-25 08:08:57 +0200
        thetext: |-
          Stefan wrote on http://mailman.science.ru.nl/pipermail/fieldtrip/2015-September/009649.html:

          I tried plotting an edf file. At line 325 the function ft_read_header seems to expect a field in the config structure that does not exist.
          Do you know if I am doing something wrong or if this is a bug?

          I am using the current field trip version downloaded from github.

          Thank you!

          Stephan


          cfg=[];
          cfg.viewmode = 'vertical';
          cfg.continuous ='yes';
          cfg.datafile = â€˜/data/test.edf';
          ft_databrowser(cfg)


          Reference to non-existent field 'headerformat'.
          Error in ft_databrowser (line 325)
            hdr = ft_read_header(cfg.headerfile, 'headerformat', cfg.headerformat);
      - +@isprivate: "0"
        commentid: "16132"
        comment_count: "1"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2015-09-25 08:44:16 +0200
        thetext: "(In reply to Robert Oostenveld from comment #0)\n\nThis works (and is according to documentation)\n\ncfg = []\ncfg.dataset = '0601_s.edf';\nft_databrowser(cfg)\n\n\nThis fails \n\ncfg = []\ncfg.datafile = '0601_s.edf'\nft_databrowser(cfg)\nReference to non-existent field 'headerformat'.\n\nError in ft_databrowser (line 325)\n  hdr = ft_read_header(cfg.headerfile, 'headerformat', cfg.headerformat);"
      - +@isprivate: "0"
        commentid: "16133"
        comment_count: "2"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2015-09-25 08:53:03 +0200
        thetext: |-
          there is no reason it should not work. I checked and the sequence

          ft_databrowser->ft_checkconfig->dataset2files

          is correctly in place, but dataset2files was not dealing with this particular case properly. This improves it.

          mac011> svn commit utilities/ft_checkconfig.m
          Sending        utilities/ft_checkconfig.m
          Transmitting file data .
          Committed revision 10690.
      - +@isprivate: "0"
        commentid: "17507"
        comment_count: "3"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2016-06-14 16:14:53 +0200
        thetext: Hereby I am closing multiple bugs that have been resolved for some time now. If you don't agree to the resolution, please reopen.
