+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "2996"
    creation_ts: 2015-10-30 16:18:00 +0100
    short_desc: filter_with_correction is not up to date in specest
    delta_ts: 2016-06-14 16:14:49 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: specest
    version: unspecified
    rep_platform: PC
    op_sys: Windows
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: litvak.vladimir
      +@name: Vladimir Litvak
    assigned_to:
      +content: r.oostenveld
      +@name: Robert Oostenveld
    cc: r.oostenveld
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "16273"
        comment_count: "0"
        who:
          +content: litvak.vladimir
          +@name: Vladimir Litvak
        bug_when: 2015-10-30 16:18:28 +0100
        thetext: |-
          I got a bug report from a colleague with the following error:

          Error using filter_with_correction
          Too many input arguments.
          In file "E:\Dropbox\spm\spm12\spm12\external\fieldtrip\specest\private\ft_preproc_bandpassfilter.m" (v10291), function "ft_preproc_bandpassfilter" at line 283.
          In file "E:\Dropbox\spm\spm12\spm12\external\fieldtrip\specest\ft_specest_hilbert.m" (v10307), function "ft_specest_hilbert" at line 171.
          In file "E:\Dropbox\spm\spm12\spm12\spm_eeg_specest_hilbert.m" (v4463), function "spm_eeg_specest_hilbert" at line 120.

          This comes down to the fact that filter_with_correction version in specest/private is different from that in preproc/private but the version of ft_preproc_bandpassfilter in specest/private is up to date and tries to call filter_with_correction with more arguments than that old version expects. Please fix.

          Thanks,

          Vladimir
      - +@isprivate: "0"
        commentid: "16285"
        comment_count: "1"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2015-11-04 17:51:55 +0100
        thetext: "mac011> svn log specest/private/filter_with_correction.m\nr7123 | roboos | 2012-12-06 22:21:38 +0100 (Thu, 06 Dec 2012) | 2 lines\n...\n\n\nmac011> svn log preproc/private/filter_with_correction.m\nr9991 | jansch | 2014-12-01 17:03:02 +0100 (Mon, 01 Dec 2014) | 1 line\n...\n\nSo the one in specest is older.\n\nThe auto sync property has not been set on either.\n\nmac011> cp preproc/private/filter_with_correction.m specest/private/\nmac011> svn propset autosync true */private/filter_with_correction.m                 \nproperty 'autosync' set on 'preproc/private/filter_with_correction.m'\nproperty 'autosync' set on 'specest/private/filter_with_correction.m'\n\n\nmac011> svn commit */private/filter_with_correction.m\nSending        preproc/private/filter_with_correction.m\nSending        specest/private/filter_with_correction.m\nTransmitting file data .\nCommitted revision 10840."
      - +@isprivate: "0"
        commentid: "17484"
        comment_count: "2"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2016-06-14 16:14:49 +0200
        thetext: Hereby I am closing multiple bugs that have been resolved for some time now. If you don't agree to the resolution, please reopen.
