+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "3356"
    creation_ts: 2017-09-25 13:37:00 +0200
    short_desc: ft_platform_supports breaks with optiom 'html'
    delta_ts: 2019-08-10 12:40:31 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: core
    version: unspecified
    rep_platform: Other
    op_sys: Linux
    bug_status: CLOSED
    resolution: WONTFIX
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: normal
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: stephen.whitmarsh
      +@name: Stephen Whitmarsh
    assigned_to: fieldtriptoolbox
    cc: j.schoffelen
    comment_sort_order: oldest_to_newest
    long_desc:
      - +@isprivate: "0"
        commentid: "18951"
        comment_count: "0"
        who:
          +content: stephen.whitmarsh
          +@name: Stephen Whitmarsh
        bug_when: 2017-09-25 13:37:19 +0200
        thetext: "Hi there,\n\nRunning MATLAB2016b on CentOS, my code that otherwise works in Windows breaks due to ft_platform_supports being called with option 'html'. There is not such a case in ft_platform_supports. This problem also only occurred after updating FT last week. Some synchronization seem to have been made last month. My problem is not restricted to this particular case, as after avoiding some other warnings, it breaks at a different place, i.e. at a different function calling e.g. ft_checkdata. \n\nI am a bit in the dark how to even make a work-around, but I expect this to be a bug.\n\nI hope this can be easily resolved. \n\nBest,\nStephen\n\n--------------\n\nOutput argument \"tf\" (and maybe others) not assigned during call to\n\"ft_platform_supports\".\n\nError in ft_notification (line 376)\n          if ft_platform_supports('html')\n\nError in ft_warning (line 63)\n  ft_notification(varargin{:});\n\nError in ft_checkconfig (line 125)\n      ft_warning('use cfg.%s instead of cfg.%s', renamed{2}, renamed{1});\n\nError in ft_prepare_leadfield (line 117)\ncfg = ft_checkconfig(cfg, 'renamed', {'vol',     'headmodel'});\n\nError in WANDER_common_filter_DICS (line 92)\n    leadfield       = ft_prepare_leadfield(cfg);\n\n\nError in launch_WANDER_batch (line 34)\nWANDER_common_filter_DICS(isubject,rootpath,force);"
      - +@isprivate: "0"
        commentid: "19034"
        comment_count: "1"
        who:
          +content: j.schoffelen
          +@name: Jan-Mathijs Schoffelen
        bug_when: 2017-11-14 09:41:37 +0100
        thetext: |-
          Hi Stephen,

          What happens if you address the issue that causes you to end up in this corner of the code?

          I.e. replace cfg.vol in your script with cfg.headmodel?
      - +@isprivate: "0"
        commentid: "19085"
        comment_count: "2"
        who:
          +content: stephen.whitmarsh
          +@name: Stephen Whitmarsh
        bug_when: 2017-11-21 14:27:51 +0100
        thetext: |-
          Hi Jan-Mathijs,
          Sorry, I overlooked your response. In the meantime it runs. I might have done as you suggested, or not. But the bug can be closed.
          Thanks,
          Stephen
      - +@isprivate: "0"
        commentid: "19086"
        comment_count: "3"
        who:
          +content: stephen.whitmarsh
          +@name: Stephen Whitmarsh
        bug_when: 2017-11-21 14:29:26 +0100
        thetext: Problem does not occur anyway, might have been caused by improper use of cfg.vol
      - +@isprivate: "0"
        commentid: "20212"
        comment_count: "4"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2019-08-10 12:34:21 +0200
        thetext: "This closes a whole series of bugs that have been resolved (either FIXED/WONTFIX/INVALID) for quite some time. \n\nIf you disagree, please file a new issue on https://github.com/fieldtrip/fieldtrip/issues."
      - +@isprivate: "0"
        commentid: "20411"
        comment_count: "5"
        who:
          +content: r.oostenveld
          +@name: Robert Oostenveld
        bug_when: 2019-08-10 12:40:31 +0200
        thetext: "This closes a whole series of bugs that have been resolved (either FIXED/WONTFIX/INVALID) for quite some time. \n\nIf you disagree, please file a new issue on https://github.com/fieldtrip/fieldtrip/issues."
