+p_xml: 'version="1.0" encoding="UTF-8" standalone="yes" '
+directive: DOCTYPE bugzilla SYSTEM "http://bugzilla.fieldtriptoolbox.org/page.cgi?id=bugzilla.dtd"
bugzilla:
  +@version: 4.4.1
  +@urlbase: http://bugzilla.fieldtriptoolbox.org/
  +@maintainer: r.oostenveld@donders.ru.nl
  bug:
    bug_id: "72"
    creation_ts: 2010-04-28 14:22:00 +0200
    short_desc: missing ft_ prefix to filetype calls in read_neuralynx_ds.m
    delta_ts: 2010-04-28 15:43:56 +0200
    reporter_accessible: "1"
    cclist_accessible: "1"
    classification_id: "1"
    classification: Unclassified
    product: FieldTrip
    component: fileio
    version: unspecified
    rep_platform: PC
    op_sys: Linux
    bug_status: CLOSED
    resolution: FIXED
    bug_file_loc:
    status_whiteboard:
    keywords:
    priority: P5
    bug_severity: blocker
    target_milestone: '---'
    everconfirmed: "1"
    reporter:
      +content: roemer.van.der.meij
      +@name: Roemer van der Meij
    assigned_to:
      +content: roemer.van.der.meij
      +@name: Roemer van der Meij
    cc: t.engelkes
    comment_sort_order: oldest_to_newest
    long_desc:
      +@isprivate: "0"
      commentid: "129"
      comment_count: "0"
      who:
        +content: roemer.van.der.meij
        +@name: Roemer van der Meij
      bug_when: 2010-04-28 14:22:12 +0200
      thetext: All filetype.m calls in read_neuralynx_ds.m were missing the ft_ prefix. It's fixed now, but I do not know whether any other read_ functions (fileio/private) are suffering the same issue.
